### ISSUE TITLE
Service currently down (both Python and Java scripts returns errors)? 

### ISSUE THREAD

**Issue by pusj** [nordnet/next-api-v2-examples#2]
Hi,

I've tried the login script for both Java and Python (for Python, I've used several different configs/ Python versions), none of these works. 

Please let me know if any additional information is needed for this issue. 

_**This is the error obtained with Python:**_

Checking NEXT API status...
<< HTTP request GET /next/2/
{
    "message": "",
    "system_running": true,
    "timestamp": 1591003566886,
    "valid_version": true
}
Logging in NEXT API...
<< HTTP request POST /next/2/login
{
    "country": "SE",
    "environment": "exttest",
    "expires_in": 300,
    "private_feed": {
        "encrypted": true,
        "hostname": "priv.api.test.nordnet.se",
        "port": 443
    },
    "public_feed": {
        "encrypted": true,
        "hostname": "pub.api.test.nordnet.se",
        "port": 443
    },
    "session_key": "b4bdb930d308e31789b6b854ceb73463cb96b4bd"
}

Connecting to feed pub.api.test.nordnet.se:443...

Traceback (most recent call last):
  File "test_program.py", line 212, in <module>
    main()
  File "test_program.py", line 187, in main
    proc.start()
  File "C:\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Python38\lib\multiprocessing\context.py", line 326, in _Popen
    return Popen(process_obj)
  File "C:\Python38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Python38\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Python38\lib\socket.py", line 272, in __getstate__
    raise TypeError(f"cannot pickle {self.__class__.__name__!r} object")
TypeError: cannot pickle 'SSLSocket' object

(nn_env) G:\Development\python-projects\nordnet-test>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python38\lib\multiprocessing\spawn.py", line 102, in spawn_main
    source_process = _winapi.OpenProcess(
OSError: [WinError 87] The parameter is incorrect

_**This is the error obtained with Java:**_

Response from checking NNAPI status
{
  "timestamp" : 1591005602482,
  "valid_version" : true,
  "system_running" : true,
  "message" : ""
}
Response from logging into the session
{
  "session_key" : "9ca03f24d540953c6d53a6cb0d6b7930fc83f440",
  "expires_in" : 300,
  "environment" : "exttest",
  "country" : "SE",
  "private_feed" : {
    "hostname" : "priv.api.test.nordnet.se",
    "port" : 443,
    "encrypted" : true
  },
  "public_feed" : {
    "hostname" : "pub.api.test.nordnet.se",
    "port" : 443,
    "encrypted" : true
  }
}
Response from Price Feed
Exception in thread "main" javax.net.ssl.SSLException: Connection reset
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:127)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1313)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:839)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at Main.main(Main.java:141)
	Suppressed: java.net.SocketException: Connection reset by peer: socket write error
		at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
		at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
		at java.base/sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:351)
		... 12 more
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1103)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
	... 8 more

Process finished with exit code 1

**Comment by iamstarkov** [comment]
can you share the full url you requesting and code samples/repositories we can reproduce your errors with?

**Comment by pusj** [comment]
Hi @iamstarkov , thanks for your reply,

I haven't done any changes or updates for this code (except for adding username and password) from this repository. So basically, is running the code "as-is". Don't get me wrong, I'd of course be happy to share any info I can regarding this, however, sharing the original repo would not help so much :-)

What is the expected outcome when e.g. running the Python example? 
What return do you get when running the Python example?

**Comment by pusj** [comment]
Hi again,

Just to start moving on this, can you @iamstarkov show what output you get when running the Python login script on a Win 10 machine?

When we have solved this item, I'll add the answer to the forum: https://api.test.nordnet.se/boards/2/topics/3062
